<?php
$block = $this;
if ($block->isAvailable()): ?>

<?php $orderCode = $block->getOrdersTrackingCode() ?>
<?php if ($orderCode): ?>
    <script type="text/javascript" src="https://eu1.snoobi.eu/extras.min.js"></script>
    <script type='text/javascript'>
        <?php echo $orderCode ?>
    </script>
<?php endif ?>

<!-- Snoobi siteanalytics V2.0 -->
<script type='text/javascript'>
    var _saq = _saq || [];
    (function() {
        var account = '<?php echo $block->getAccount() ?>';
        var snbpagename = '';
        var snbsection = '';
        var snbcookies = '<?php echo $block->getCookies() ?>';
        var anchors = '<?php echo $block->getAnchors() ?>';
        var snbscript = document.createElement('script');
        snbscript.type = 'text/javascript';
        snbscript.async= true;
        snbscript.src = ('https:' == document.location.protocol ? 'https://' : 'http://')
            + 'eu2.snoobi.eu/?account=' + account
            + '&page_name=' + snbpagename
            + '&section=' + snbsection
            + '&anchors=' + anchors
            + '&cookies=' + snbcookies;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(snbscript, s);
    })();
</script>

<?php endif ?>
